apiVersion: apps/v1
kind: Deployment
metadata:
  name: springuma
  labels:
    app: springuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springuma
  template:
    metadata:
      labels:
        app: springuma
    spec:
      containers:
        - name: springuma
          # The workflow replaces <DOCKER_IMAGE_PLACEHOLDER> with the built image
          image: <DOCKER_IMAGE_PLACEHOLDER>
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
